
title: kevin buckley
email: kbuckley17@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  things I learn in tech
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-hydeout
sidebar_home_link:  false

plugins:
  - jekyll-feed

repo: "https://github.com/kevinbuckley"
twitter: "https://twitter.com/kbucktothemax"